<?php

function login_update_9001() {
  $values = [
    'block_every' => 5,
    'base_delay' => 30,
    'max_delay' => 300,
    'reset_window' => 3600,
    'permanent_block_at' => 50,
    'flood_register_window' => 3600,
  ];

  $config = \Drupal::configFactory()->getEditable('login.settings');
  foreach ($values as $key => $val) {
    if ($config->get($key) === NULL) {
      $config->set($key, $val);
    }
  }
  $config->save();

  return t('Added default login.settings configuration.');
}
